'''
central place to list the features to be used in training
'''

general = [
  #"flavour",
  #"vertexCategory",
  #"vertexLeptonCategory",
  "jetPt",
  #"trackJetPt",
  "jetEta",
  "trackSip2dSig_0", #"trackSip2dSig_1",#"trackSip2dSig_2",
  "trackSip3dSig_0", #"trackSip3dSig_1",#"trackSip3dSig_2",
  "trackSip2dVal_0", #"trackSip2dVal_1", "trackSip2dVal_2",
  "trackSip3dVal_0", #"trackSip3dVal_1", "trackSip3dVal_2",
  "trackPtRel_0", #"trackPtRel_1",# "trackPtRel_2",
  "trackPPar_0", #"trackPPar_1",# "trackPPar_2",
  "trackEtaRel_0",#"trackEtaRel_1",# "trackEtaRel_2",
  "trackDeltaR_0", #"trackDeltaR_1",# "trackDeltaR_2",
  "trackPtRatio_0", #"trackPtRatio_1",# "trackPtRatio_2",
  "trackPParRatio_0",# "trackPParRatio_1",# "trackPParRatio_2",
  "trackJetDist_0",#"trackJetDist_1",# "trackJetDist_2",
  "trackDecayLenVal_0",# "trackDecayLenVal_1",# "trackDecayLenVal_2",
  "jetNSecondaryVertices",
  "jetNTracks",
  "trackSumJetEtRatio",
  "trackSumJetDeltaR",
  "jetPtD_0"
]

vertex = [
  "vertexMass_0",
  "vertexEnergyRatio_0",
  "trackSip2dSigAboveCharm_0",
  "trackSip3dSigAboveCharm_0",
  "flightDistance2dSig_0",
  "flightDistance3dSig_0",
  "flightDistance2dVal_0",
  "flightDistance3dVal_0",
  "vertexJetDeltaR_0",
  "vertexNTracks_0",
  "trackSip2dValAboveCharm_0",
  "trackSip3dValAboveCharm_0",
  #"vertexFitProb_0",
  #"chargedHadronEnergyFraction",
  #"neutralHadronEnergyFraction",
  #"photonEnergyFraction",
  #"electronEnergyFraction",
  #"muonEnergyFraction",
  "massVertexEnergyFraction_0",
  "vertexBoostOverSqrtJetPt_0",
]

leptons = [
  "leptonPtRel_0",#"leptonPtRel_1",#"leptonPtRel_2",
  #"leptonSip3d_0",#"leptonSip3d_1",#"leptonSip3d_2",
  "leptonDeltaR_0",#"leptonDeltaR_1",#"leptonDeltaR_2",
  #"leptonRatioRel_0",#"leptonRatioRel_1",#"leptonRatioRel_2",
  #"leptonEtaRel_0",#"leptonEtaRel_1",#"leptonEtaRel_2",
  "leptonRatio_0",#"leptonRatio_1",#"leptonRatio_2",
  ]
  
feature_defaults = {
   'jetPt' : {'default' : 0, 'type' : 'f'},
   'jetEta': {'default' : -10, 'type' : 'f'},
   'jetPtD' : {'default' : -10, 'type' : 'f', 'max_idx': 1},
   'relConcentricEnergyAroundJetAxis' : {'default' : -10, 'type' : 'f', 'max_idx': 8},
   'correctedSVMass': {'default': -0.1, 'max_idx': 1, 'type': 'f'},    
   'muonMultiplicity': {'default': -1, 'type': 'i'},    
   'trackPPar': {'default': -1, 'max_idx': 3, 'type': 'f'},
   'flightDistance3dSig': {'default': -1, 'max_idx': 1, 'type': 'f'},
   'trackSip2dVal': {'default': -1, 'max_idx': 3, 'type': 'f'},
   'vertexBoostOverSqrtJetPt': {'default': -0.1, 'max_idx': 1, 'type': 'f'}, 
   'trackEtaRel': {'default': -1, 'max_idx': 3, 'type': 'f'}, 
   'vertexMass': {'default': -0.1, 'max_idx': 1, 'type': 'f'}, 
   'trackDecayLenVal': {'default': -0.1, 'max_idx': 3, 'type': 'f'}, 
   'trackJetPt': {'default': -1, 'type': 'f'}, 
   'neutralHadronMultiplicity': {'default': -1, 'type': 'i'}, 
   'flightDistance3dVal': {'default': -0.1, 'max_idx': 1, 'type': 'f'}, 
   'trackJetDist': {'default': -0.1, 'max_idx': 3, 'type': 'f'}, 
   'leptonSip3d': {'default': -10000, 'max_idx': 3, 'type': 'f'}, 
   'neutralHadronEnergyFraction': {'default': -0.1, 'type': 'f'}, 
   'trackPtRatio': {'default': -0.1, 'max_idx': 3, 'type': 'f'}, 
   'hadronMultiplicity': {'default': -1, 'type': 'i'}, 
   'trackSumJetEtRatio': {'default': -0.1, 'type': 'f'}, 
   'vertexJetDeltaR': {'default': -0.1, 'max_idx': 1, 'type': 'f'}, 
   'leptonRatioRel': {'default': -1, 'max_idx': 3, 'type': 'f'}, 
   'chargedHadronMultiplicity': {'default': -1, 'type': 'i'}, 
   'jetNTracks': {'default': -0.1, 'type': 'i'}, 
   'trackDeltaR': {'default': -0.1, 'max_idx': 3, 'type': 'f'}, 
   'vertexFitProb': {'default': -1, 'max_idx': 1, 'type': 'f'}, 
   'trackSip3dValAboveCharm': {'default': -1, 'max_idx': 1, 'type': 'f'}, 
   'jetEta': {'default': -3, 'type': 'f'}, 
   'leptonDeltaR': {'default': -1, 'max_idx': 3, 'type': 'f'}, 
   'hadronPhotonMultiplicity': {'default': -1, 'type': 'i'}, 
   'leptonPtRel': {'default': -1, 'max_idx': 3, 'type': 'f'}, 
   'flightDistance2dVal': {'default': -0.1, 'max_idx': 1, 'type': 'f'}, 
   'trackSumJetDeltaR': {'default': -0.1, 'type': 'f'}, 
   'photonMultiplicity': {'default': -1, 'type': 'i'}, 
   'chargedHadronEnergyFraction': {'default': -0.1, 'type': 'f'}, 
   'trackSip3dSigAboveQuarterCharm': {'default': -999, 'max_idx': 1, 'type': 'f'}, 
   'vertexLeptonCategory': {'default': -1, 'type': 'i'}, 
   'massVertexEnergyFraction': {'default': -0.1, 'max_idx': 1, 'type': 'f'}, 
   'trackSip2dSig': {'default': -100, 'max_idx': 3, 'type': 'f'}, 
   'flightDistance2dSig': {'default': -1, 'max_idx': 1, 'type': 'f'}, 
   'jetPt': {'default': -1, 'type': 'f'}, 
   'totalMultiplicity': {'default': -1, 'type': 'i'}, 
   'trackSip2dValAboveCharm': {'default': -1, 'max_idx': 1, 'type': 'f'}, 
   'electronEnergyFraction': {'default': -0.1, 'type': 'f'}, 
   'jetNSecondaryVertices': {'default': 0, 'type': 'i'}, 
   'trackSip2dSigAboveCharm': {'default': -999, 'max_idx': 1, 'type': 'f'}, 
   'vertexCategory': {'default': -1, 'type': 'i'}, 
   'vertexEnergyRatio': {'default': -10, 'max_idx': 1, 'type': 'f'}, 
   'photonEnergyFraction': {'default': -0.1, 'type': 'f'}, 
   'flavour': {'default': -1, 'type': 'i'}, 
   'muonEnergyFraction': {'default': -0.1, 'type': 'f'}, 
   'vertexNTracks': {'default': 0, 'max_idx': 1, 'type': 'i'}, 
   'trackSip2dSigAboveQuarterCharm': {'default': -999, 'max_idx': 1, 'type': 'f'}, 
   'trackSip3dVal': {'default': -1, 'max_idx': 3, 'type': 'f'}, 
   'leptonRatio': {'default': -1, 'max_idx': 3, 'type': 'f'}, 
   'trackPtRel': {'default': -1, 'max_idx': 3, 'type': 'f'}, 
   'leptonEtaRel': {'default': -1, 'max_idx': 3, 'type': 'f'}, 
   'trackPParRatio': {'default': 1.1, 'max_idx': 3, 'type': 'f'}, 
   'trackSip3dSig': {'default': -100, 'max_idx': 3, 'type': 'f'}, 
   'trackSip3dSigAboveCharm': {'default': -999, 'max_idx': 1, 'type': 'f'}, 
   'electronMultiplicity': {'default': -1, 'type': 'i'}
}
